version: "3.8"

services:
  client:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    command: ["npm", "start"]